name: Sample workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Tou.md
        uses: joaopalmeiro/tou@v0.2.3
        with:
          ignore-403-forbidden: false
